# Generated by Django 4.0.5 on 2022-06-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Messages',
        ),
    ]
