# Generated by Django 4.0.5 on 2022-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Контактная информация'),
        ),
    ]
